INTERNATIONAL = [
    # General terms related to international or global context
    "international",
    "global",
    "world",
    "multinational",
    "cross-border",
    "worldwide",
    "globalization",
    "foreign affairs",
    "diplomacy",
    "international relations",
    "geopolitical",
    "geopolitics",
    "intergovernmental",
    "transnational",
    "foreign policy",
    "foreign aid",
    "supranational",
    "bilateral",
    "multilateral",
    "cross-national",
    "international cooperation",
    "global governance",
    "global impact",
    "international community",
    "world leaders",
    "global leaders",
    "global partnerships",
    "international law",
    "international treaties",
    # International organizations and alliances
    "un",
    "united nations",
    "unhcr",
    "unesco",
    "unicef",
    "who",
    "world health organization",
    "imf",
    "international monetary fund",
    "world bank",
    "world trade organization",
    "wto",
    "international court of justice",
    "icj",
    "international criminal court",
    "icc",
    "oecd",
    "organization for economic cooperation and development",
    "g7",
    "g20",
    "g8",
    "g77",
    "nato",
    "north atlantic treaty organization",
    "eu",
    "european union",
    "au",
    "african union",
    "asean",
    "association of southeast asian nations",
    "mercosur",
    "opec",
    "organization of petroleum exporting countries",
    "commonwealth",
    "arab league",
    "gulf cooperation council",
    "gcc",
    "interpol",
    "amnesty international",
    "international red cross",
    "greenpeace",
    "doctors without borders",
    "médecins sans frontières",
    "human rights watch",
    # International events and summits
    "cop",
    "conference of the parties",
    "climate summit",
    "paris agreement",
    "g7 summit",
    "g20 summit",
    "world economic forum",
    "davos",
    "un general assembly",
    "munich security conference",
    "nuclear summit",
    "geneva conventions",
    "peace talks",
    "international negotiations",
    "global conference",
    "global forum",
    "international summit",
    "trade negotiations",
    "world trade forum",
    "international peace summit",
    # International finance and trade
    "global economy",
    "international trade",
    "free trade",
    "foreign investment",
    "multinational corporations",
    "world bank",
    "imf",
    "world economic forum",
    "forex",
    "global markets",
    "global recession",
    "currency exchange",
    "trade wars",
    "tariffs",
    "sanctions",
    "foreign direct investment",
    "global supply chain",
    "export",
    "import",
    "balance of trade",
    "trade deficit",
    "trade surplus",
    "world trade organization",
    "global banking",
    "international finance",
    "cryptocurrency regulations",
    "global stock markets",
    # Human rights and international law
    "human rights",
    "international human rights",
    "war crimes",
    "crimes against humanity",
    "genocide",
    "refugee crisis",
    "asylum",
    "political asylum",
    "international law",
    "international justice",
    "war tribunals",
    "migrant crisis",
    "forced migration",
    "human trafficking",
    "international criminal court",
    "human rights abuses",
    "international labor rights",
    "universal declaration of human rights",
    "icj",
    "international court of justice",
    "geneva conventions",
    "humanitarian intervention",
    "peacekeeping",
    "peacekeeping forces",
    "refugee camps",
    "international aid",
    "ngo",
    "non-governmental organization",
    "unhcr",
    "united nations high commissioner for refugees",
    "humanitarian law",
    # Major international conflicts and issues
    "conflict zones",
    "war",
    "international conflict",
    "international crisis",
    "global crisis",
    "civil war",
    "terrorism",
    "counterterrorism",
    "nuclear proliferation",
    "nuclear disarmament",
    "arms control",
    "sanctions",
    "embargo",
    "international sanctions",
    "cyber warfare",
    "global cybersecurity",
    "piracy",
    "international terrorism",
    "global terrorism",
    "international security",
    "peace talks",
    "un intervention",
    "military intervention",
    "international coalition",
    "global conflict resolution",
    "border disputes",
    "sovereignty disputes",
    "international peacekeepers",
    # International treaties and agreements
    "international treaty",
    "bilateral agreement",
    "multilateral agreement",
    "trade agreements",
    "paris climate agreement",
    "kyoto protocol",
    "nuclear non-proliferation treaty",
    "arms trade treaty",
    "free trade agreement",
    "nafta",
    "usmca",
    "tpp",
    "trans-pacific partnership",
    "transatlantic trade and investment partnership",
    "ttip",
    "climate agreements",
    "united nations conventions",
    "international accords",
    "global pacts",
    "geneva accords",
    "peace treaties",
    "international defense agreements",
    # International development and aid
    "foreign aid",
    "international development",
    "global development",
    "humanitarian assistance",
    "global poverty",
    "sustainable development goals",
    "sdgs",
    "international ngos",
    "development aid",
    "third world development",
    "developing nations",
    "global inequality",
    "disaster relief",
    "global education",
    "international food aid",
    "unicef",
    "global health",
    "international health organizations",
    "who",
    "world health organization",
    "global vaccination programs",
    "international development banks",
    "world bank",
    "microfinance",
    "international donors",
    # International environment and climate
    "climate change",
    "global warming",
    "international climate agreements",
    "paris agreement",
    "cop26",
    "biodiversity",
    "deforestation",
    "ozone layer",
    "global emissions",
    "greenhouse gases",
    "carbon footprint",
    "carbon emissions",
    "climate crisis",
    "global environmental policy",
    "international environmental law",
    "climate refugees",
    "international conservation",
    "global energy policy",
    "renewable energy",
    "sustainable energy",
    "global climate action",
    "climate adaptation",
    "climate mitigation",
    "environmental ngos",
    "global pollution",
    "ocean conservation",
    "international wildlife protection",
    # International transportation and travel
    "international travel",
    "global tourism",
    "international flights",
    "global airlines",
    "visa",
    "passport",
    "customs",
    "immigration",
    "international borders",
    "global transportation",
    "international shipping",
    "global logistics",
    "international trade routes",
    "aviation agreements",
    "maritime law",
    "global supply chains",
    "international airports",
    "international airlines",
    "global travel restrictions",
    "international tourism",
    "schengen visa",
    "global visas",
    "international embassies",
    # International sports and culture
    "olympics",
    "summer olympics",
    "winter olympics",
    "fifa world cup",
    "international sports",
    "world cup",
    "international tournaments",
    "global sporting events",
    "cultural exchange",
    "international festivals",
    "global media",
    "international art",
    "world heritage sites",
    "unesco world heritage",
    "international film festivals",
    "global music awards",
    "international fashion",
    "cultural diplomacy",
    "global cultural impact",
    "international exhibitions",
    "global sports organizations",
    "fifa",
    "ioc",
    "international olympic committee",
    # International technology and science
    "global tech companies",
    "international tech regulation",
    "global cybersecurity",
    "international space station",
    "iss",
    "nasa",
    "global satellites",
    "international space exploration",
    "global scientific research",
    "international patent law",
    "global intellectual property",
    "international tech conferences",
    "cross-border data",
    "global data privacy",
    "international ai development",
    "global innovation",
    "global scientific collaboration",
    "international clinical trials",
    "international space treaties",
    "global internet governance",
    # Multinational corporations and business
    "multinational corporations",
    "global companies",
    "transnational corporations",
    "international mergers",
    "international acquisitions",
    "global markets",
    "international business",
    "global supply chains",
    "international competition",
    "global brand",
    "international headquarters",
    "global workforce",
    "foreign subsidiaries",
    "international business law",
    "cross-border mergers",
    "global entrepreneurship",
    "international startups",
    "global trade regulations",
    "international franchise",
    "global e-commerce",
]

CHINA_REGIONS = [
    "china",
    "beijing",
    "shanghai",
    "tianjin",
    "chongqing",  # Municipalities
    "guangdong",
    "shandong",
    "jiangsu",
    "zhejiang",
    "fujian",
    "anhui",
    "jiangxi",
    "henan",
    "hunan",
    "hubei",  # Eastern and Central provinces
    "sichuan",
    "guizhou",
    "yunnan",
    "shanxi",
    "gansu",
    "qinghai",
    "hainan",
    "heilongjiang",  # Western and Northern provinces
    "liaoning",
    "jilin",
    "hebei",
    "shanxi",
    "inner mongolia",  # Northern regions
    "xinjiang",
    "tibet",
    "ningxia",
    "guangxi",
    "mongolia",
    "xizang",  # Autonomous regions
    "macau",
    "hong kong",
    "taiwan",  # Special regions
    "nanjing",
    "shenzhen",
    "guangzhou",
    "wuhan",
    "chengdu",
    "hangzhou",
    "xi'an",
    "suzhou",
    "qingdao",
    "dalian",
    "nanning",  # Major cities
    "harbin",
    "changchun",
    "zhengzhou",
    "changsha",
    "xiamen",
    "shijiazhuang",
    "urumqi",
    "lhasa",
    "haikou",
    "kunming",  # More cities and capitals
    "peking",
    "nanjing",
    "wenzhou",
    "foshan",
    "dongguan",
    "ningbo",
    "shantou",
    "zhuhai",
    "zhongshan",
    "jiangmen",
    "shenyang",  # Additional significant cities
]

SOUTH_ASIA_REGIONS = [
    "india",
    "new delhi",
    "mumbai",
    "kolkata",
    "bangalore",
    "chennai",
    "hyderabad",
    "ahmedabad",
    "pune",
    "jaipur",
    "lucknow",  # Major cities in India
    "delhi",
    "gujarat",
    "maharashtra",
    "tamil nadu",
    "karnataka",
    "west bengal",
    "kerala",
    "uttar pradesh",
    "rajasthan",  # Indian states
    "punjab",
    "haryana",
    "bihar",
    "madhya pradesh",
    "andhra pradesh",
    "odisha",
    "assam",
    "uttarakhand",
    "goa",
    "jharkhand",
    "chhattisgarh",  # More Indian states
    "pakistan",
    "islamabad",
    "karachi",
    "lahore",
    "peshawar",
    "quetta",
    "rawalpindi",
    "multan",
    "faisalabad",
    "sindh",
    "punjab",
    "balochistan",
    "khyber pakhtunkhwa",  # Pakistan cities and regions
    "bangladesh",
    "dhaka",
    "chittagong",
    "khulna",
    "rajshahi",
    "sylhet",
    "barisal",
    "rangpur",
    "mymensingh",  # Bangladesh cities and regions
    "sri lanka",
    "colombo",
    "kandy",
    "galle",
    "jaffna",
    "negombo",
    "anuradhapura",
    "trincomalee",  # Sri Lanka cities and regions
    "nepal",
    "kathmandu",
    "pokhara",
    "lalitpur",
    "bhaktapur",
    "biratnagar",
    "janakpur",
    "lumbini",  # Nepal cities and regions
    "bhutan",
    "thimphu",
    "paro",
    "phuentsholing",
    "punakha",
    "samdrup jongkhar",
    "wangdue phodrang",  # Bhutan cities and regions
    "maldives",
    "male",
    "addu",
    "fuvahmulah",
    "hulhumale",
    "gan",  # Maldives cities and regions
]

SOUTHEAST_ASIA_REGIONS = [
    "indonesia",
    "jakarta",
    "surabaya",
    "bandung",
    "medan",
    "semarang",
    "makassar",
    "bali",
    "yogyakarta",
    "papua",  # Indonesia cities and regions
    "philippines",
    "manila",
    "cebu",
    "davao",
    "quezon city",
    "makati",
    "zamboanga",
    "iloilo",
    "batangas",
    "mindanao",
    "luzon",
    "visayas",  # Philippines cities and regions
    "vietnam",
    "hanoi",
    "ho chi minh city",
    "danang",
    "haiphong",
    "hue",
    "can tho",
    "vung tau",
    "nha trang",
    "mekong delta",  # Vietnam cities and regions
    "thailand",
    "bangkok",
    "chiang mai",
    "phuket",
    "pattaya",
    "krabi",
    "hat yai",
    "nonthaburi",
    "udon thani",
    "surat thani",
    "ayutthaya",  # Thailand cities and regions
    "myanmar",
    "naypyidaw",
    "yangon",
    "mandalay",
    "bagan",
    "mon state",
    "shan state",
    "rakhine",
    "sagaing",  # Myanmar cities and regions
    "malaysia",
    "kuala lumpur",
    "penang",
    "johor bahru",
    "malacca",
    "sabah",
    "sarawak",
    "selangor",
    "ipoh",
    "kuantan",
    "langkawi",  # Malaysia cities and regions
    "cambodia",
    "phnom penh",
    "siem reap",
    "battambang",
    "sihanoukville",
    "kampot",
    "kampong cham",
    "pursat",  # Cambodia cities and regions
    "laos",
    "vientiane",
    "luang prabang",
    "savannakhet",
    "pakse",
    "champasak",
    "xieng khouang",
    "bokeo",  # Laos cities and regions
    "brunei",
    "bandar seri begawan",
    "kuala belait",
    "tutong",
    "seria",  # Brunei cities and regions
    "singapore",
    "jurong",
    "sentosa",
    "changi",
    "yishun",
    "woodlands",  # Singapore areas
    "timor-leste",
    "dili",
    "baucau",
    "manatuto",
    "liquica",
    "ermera",  # Timor-Leste cities and regions
]

EAST_ASIA_REGIONS = [
    "japan",
    "tokyo",
    "osaka",
    "kyoto",
    "yokohama",
    "nagoya",
    "sapporo",
    "fukuoka",
    "hiroshima",
    "sendai",
    "kobe",  # Japan cities
    "hokkaido",
    "honshu",
    "kyushu",
    "shikoku",
    "okinawa",
    "nagasaki",
    "kawasaki",
    "kanagawa",
    "chiba",
    "niigata",  # Japan regions and prefectures
    "south korea",
    "seoul",
    "busan",
    "incheon",
    "daegu",
    "daejeon",
    "gwangju",
    "ulsan",
    "jeju",
    "suwon",
    "gyeonggi",  # South Korea cities and regions
    "north korea",
    "pyongyang",
    "kaesong",
    "nampo",
    "wonsan",
    "hamhung",
    "chongjin",
    "sinuiju",
    "hyesan",  # North Korea cities
    "taiwan",
    "taipei",
    "kaohsiung",
    "taichung",
    "tainan",
    "hsinchu",
    "keelung",
    "chiayi",
    "pingtung",
    "yilan",
    "hualien",  # Taiwan cities and regions
    "hong kong",
    "kowloon",
    "new territories",
    "lantau island",
    "causeway bay",
    "tsim sha tsui",
    "sha tin",  # Hong Kong regions and areas
    "macau",
    "cotai",
    "taipa",
    "coloane",
    "macau peninsula",  # Macau regions and areas
]

CENTRAL_ASIA_REGIONS = [
    "kazakhstan",
    "almaty",
    "nur-sultan",
    "astana",
    "shymkent",
    "karaganda",
    "aktobe",
    "atyrau",
    "pavlodar",
    "taraz",
    "uralsk",  # Kazakhstan cities and regions
    "uzbekistan",
    "tashkent",
    "samarkand",
    "bukhara",
    "namangan",
    "andijan",
    "fergana",
    "nukus",
    "khiva",
    "qarshi",
    "termez",  # Uzbekistan cities and regions
    "turkmenistan",
    "ashgabat",
    "turkmenabat",
    "mary",
    "dashoguz",
    "balkanabat",
    "tejen",
    "kerki",
    "serdar",  # Turkmenistan cities and regions
    "tajikistan",
    "dushanbe",
    "khujand",
    "kulob",
    "bokhtar",
    "isfara",
    "panjakent",
    "qarteghin",
    "gorno-badakhshan",  # Tajikistan cities and regions
    "kyrgyzstan",
    "bishkek",
    "osh",
    "jalal-abad",
    "karakol",
    "tokmok",
    "talas",
    "uzgen",
    "naryn",
    "batken",
    "issyk-kul",  # Kyrgyzstan cities and regions
]

WEST_ASIA_REGIONS = [
    "iran",
    "tehran",
    "mashhad",
    "isfahan",
    "shiraz",
    "tabriz",
    "karaj",
    "qom",
    "ahvaz",
    "urmia",
    "kermanshah",
    "bandar abbas",  # Iran cities and regions
    "iraq",
    "baghdad",
    "basra",
    "mosul",
    "erbil",
    "sulaymaniyah",
    "najaf",
    "karbala",
    "kirkuk",
    "fallujah",
    "nasiriyah",
    "diwaniyah",  # Iraq cities and regions
    "syria",
    "damascus",
    "aleppo",
    "homs",
    "hama",
    "latakia",
    "deir ez-zor",
    "raqqa",
    "tartus",
    "idlib",
    "qamishli",  # Syria cities and regions
    "lebanon",
    "beirut",
    "tripoli",
    "sidon",
    "tyre",
    "baalbek",
    "zahle",
    "jounieh",
    "nabatieh",  # Lebanon cities and regions
    "jordan",
    "amman",
    "zarqa",
    "irbid",
    "aqaba",
    "madaba",
    "mafraq",
    "karak",
    "salt",  # Jordan cities and regions
    "israel",
    "jerusalem",
    "tel aviv",
    "haifa",
    "beer sheva",
    "netanya",
    "ashdod",
    "eilat",
    "tiberias",
    "nazareth",
    "acre",  # Israel cities and regions
    "palestine",
    "gaza",
    "ramallah",
    "nablus",
    "hebron",
    "bethlehem",
    "jericho",
    "rafah",
    "jenin",
    "khan younis",  # Palestine cities and regions
    "saudi arabia",
    "riyadh",
    "jeddah",
    "mecca",
    "medina",
    "dammam",
    "khobar",
    "jubail",
    "tabuk",
    "abha",
    "najran",
    "al kharj",
    "al hofuf",  # Saudi Arabia cities and regions
    "uae",
    "dubai",
    "abu dhabi",
    "sharjah",
    "ajman",
    "fujairah",
    "ras al khaimah",
    "umm al quwain",
    "al ain",  # UAE cities and regions
    "qatar",
    "doha",
    "al wakrah",
    "al khor",
    "al rayyan",
    "al daayen",
    "umm salal",  # Qatar cities and regions
    "kuwait",
    "kuwait city",
    "jahra",
    "salmiya",
    "hawalli",
    "fahaheel",
    "mangaf",
    "farwaniya",  # Kuwait cities and regions
    "oman",
    "muscat",
    "salalah",
    "nizwa",
    "sohar",
    "sur",
    "buraimi",
    "ibra",
    "rustaq",
    "khasab",  # Oman cities and regions
    "yemen",
    "sanaa",
    "aden",
    "taiz",
    "hudaydah",
    "mukalla",
    "ib",
    "dhamar",
    "marib",
    "sadah",  # Yemen cities and regions
    "bahrain",
    "manama",
    "muharraq",
    "riffa",
    "hamad town",
    "isa town",
    "sitra",  # Bahrain cities and regions
    "turkey",
    "ankara",
    "istanbul",
    "izmir",
    "bursa",
    "antalya",
    "adana",
    "konya",
    "gaziantep",
    "mersin",
    "kayseri",
    "samsun",  # Turkey cities and regions
]
RUSSIA_REGIONS = [
    "russia",
    "moscow",
    "saint petersburg",
    "novosibirsk",
    "yekaterinburg",
    "nizhny novgorod",
    "kazan",
    "chelyabinsk",
    "omsk",
    "samara",
    "rostov-on-don",
    "ufa",
    "krasnoyarsk",
    "voronezh",
    "perm",
    "volgograd",
    "krasnodar",
    "sochi",
    "irkutsk",  # Major cities
    "vladivostok",
    "kaliningrad",
    "murmansk",
    "arkhangelsk",
    "yakutsk",
    "ulan-ude",
    "sevastopol",
    "grozny",
    "saratov",
    "tolyatti",  # More cities and regions
    "siberia",
    "ural",
    "far east",
    "crimea",
    "caucasus",
    "altai",
    "karelia",
    "khabarovsk",  # Regions and territories
    "tula",
    "tver",
    "smolensk",
    "bryansk",
    "ryazan",
    "yaroslavl",
    "vologda",
    "kostroma",
    "ivanovo",
    "tambov",  # Central Russia regions
    "astrakhan",
    "belgorod",
    "lipetsk",
    "kursk",
    "orenburg",
    "izhevsk",
    "vladikavkaz",
    "mahachkala",
    "nizhnekamsk",  # Southern and eastern regions
    "komi republic",
    "dagestan",
    "bashkortostan",
    "tatarstan",
    "khakassia",
    "buryatia",
    "sakhalin",
    "chukotka",  # Autonomous republics and regions
]

EUROPE_REGIONS = [
    # Western Europe
    "united kingdom",
    "england",
    "scotland",
    "wales",
    "northern ireland",
    "london",
    "birmingham",
    "manchester",
    "edinburgh",
    "glasgow",
    "cardiff",
    "belfast",  # UK
    "france",
    "paris",
    "marseille",
    "lyon",
    "toulouse",
    "nice",
    "nantes",
    "strasbourg",
    "bordeaux",
    "lille",
    "rennes",  # France
    "germany",
    "berlin",
    "munich",
    "frankfurt",
    "hamburg",
    "cologne",
    "stuttgart",
    "dusseldorf",
    "dortmund",
    "leipzig",
    "hanover",
    "bremen",  # Germany
    "netherlands",
    "amsterdam",
    "rotterdam",
    "the hague",
    "utrecht",
    "eindhoven",
    "groningen",
    "maastricht",  # Netherlands
    "belgium",
    "brussels",
    "antwerp",
    "ghent",
    "bruges",
    "liege",
    "charleroi",  # Belgium
    "luxembourg",
    "luxembourg city",
    "esch-sur-alzette",
    "dudelange",  # Luxembourg
    "switzerland",
    "zurich",
    "geneva",
    "basel",
    "lausanne",
    "bern",
    "lucerne",  # Switzerland
    "austria",
    "vienna",
    "salzburg",
    "graz",
    "innsbruck",
    "linz",  # Austria
    # Southern Europe
    "italy",
    "rome",
    "milan",
    "naples",
    "turin",
    "palermo",
    "genoa",
    "florence",
    "bologna",  # Italy
    "spain",
    "madrid",
    "barcelona",
    "valencia",
    "seville",
    "malaga",
    "zaragoza",
    "bilbao",
    "alicante",
    "granada",  # Spain
    "portugal",
    "lisbon",
    "porto",
    "braga",
    "coimbra",
    "faro",
    "madeira",
    "azores",  # Portugal
    "greece",
    "athens",
    "thessaloniki",
    "patras",
    "heraklion",
    "volos",
    "larissa",
    "crete",
    "corfu",
    "rhodes",  # Greece
    "malta",
    "valletta",
    "sliema",
    "birgu",
    "birkirkara",  # Malta
    # Northern Europe
    "sweden",
    "stockholm",
    "gothenburg",
    "malmo",
    "uppsala",  # Sweden
    "norway",
    "oslo",
    "bergen",
    "trondheim",
    "stavanger",
    "tromso",  # Norway
    "denmark",
    "copenhagen",
    "aarhus",
    "odense",
    "aalborg",  # Denmark
    "finland",
    "helsinki",
    "espoo",
    "tampere",
    "oulu",
    "vantaa",  # Finland
    "iceland",
    "reykjavik",
    "akureyri",
    "kopavogur",
    "hafnarfjordur",  # Iceland
    # Central and Eastern Europe
    "poland",
    "warsaw",
    "krakow",
    "gdansk",
    "poznan",
    "wroclaw",
    "lodz",
    "szczecin",  # Poland
    "czech republic",
    "prague",
    "brno",
    "ostrava",
    "plzen",
    "olomouc",
    "pardubice",  # Czech Republic
    "hungary",
    "budapest",
    "szeged",
    "debrecen",
    "pecs",
    "gyor",
    "miskolc",  # Hungary
    "slovakia",
    "bratislava",
    "kosice",
    "trnava",
    "zilina",
    "nitra",  # Slovakia
    "romania",
    "bucharest",
    "cluj-napoca",
    "timisoara",
    "iasi",
    "constanta",
    "brasov",
    "sibiu",  # Romania
    "bulgaria",
    "sofia",
    "plovdiv",
    "varna",
    "burgas",
    "ruse",
    "pleven",  # Bulgaria
    # The Baltic States
    "estonia",
    "tallinn",
    "tartu",
    "narva",
    "parnu",  # Estonia
    "latvia",
    "riga",
    "daugavpils",
    "liepaja",
    "jelgava",  # Latvia
    "lithuania",
    "vilnius",
    "kaunas",
    "klaipeda",
    "siauliai",
    "panevezys",  # Lithuania
    # The Balkans
    "slovenia",
    "ljubljana",
    "maribor",
    "koper",
    "celje",  # Slovenia
    "croatia",
    "zagreb",
    "split",
    "rijeka",
    "zadar",
    "dubrovnik",  # Croatia
    "serbia",
    "belgrade",
    "novi sad",
    "nis",
    "kragujevac",
    "subotica",  # Serbia
    "bosnia and herzegovina",
    "sarajevo",
    "banja luka",
    "mostar",
    "tuzla",
    "zenica",  # Bosnia and Herzegovina
    "montenegro",
    "podgorica",
    "kotor",
    "budva",
    "niksic",
    "herceg novi",  # Montenegro
    "north macedonia",
    "skopje",
    "bitola",
    "ohrid",
    "tetovo",
    "prilep",  # North Macedonia
    "albania",
    "tirana",
    "durres",
    "vlore",
    "shkoder",
    "fier",  # Albania
    "kosovo",
    "pristina",
    "prizren",
    "gjakova",
    "peja",
    "mitrovica",  # Kosovo
    # Other European regions
    "ukraine",
    "kyiv",
    "kharkiv",
    "dnipro",
    "odesa",
    "lviv",
    "zaporizhzhia",
    "vinnytsia",  # Ukraine
    "belarus",
    "minsk",
    "gomel",
    "mogilev",
    "vitebsk",
    "hrodna",
    "brest",  # Belarus
    "moldova",
    "chisinau",
    "balti",
    "tiraspol",
    "cahul",  # Moldova
    "georgia",
    "tbilisi",
    "batumi",
    "kutaisi",
    "rustavi",  # Georgia
    "armenia",
    "yerevan",
    "gyumri",
    "vanadzor",
    "hrazdan",
    "erebuni",  # Armenia
    "azerbaijan",
    "baku",
    "ganca",
    "sumqayit",
    "mingachevir",
    "nakhchivan",  # Azerbaijan
]
AFRICA_REGIONS = [
    # Northern Africa
    "algeria",
    "algiers",
    "oran",
    "constantine",
    "annaba",
    "blida",
    "batna",
    "setif",
    "bejaia",
    "tlemcen",  # Algeria cities and regions
    "egypt",
    "cairo",
    "alexandria",
    "giza",
    "luxor",
    "aswan",
    "port said",
    "suez",
    "ismailia",
    "mansoura",
    "tanta",
    "zagazig",
    "fayoum",  # Egypt cities and regions
    "libya",
    "tripoli",
    "benghazi",
    "misrata",
    "sabha",
    "derna",
    "zawiya",
    "zintan",  # Libya cities and regions
    "morocco",
    "rabat",
    "casablanca",
    "marrakech",
    "fes",
    "tangier",
    "meknes",
    "agadir",
    "oujda",
    "tetouan",  # Morocco cities and regions
    "tunisia",
    "tunis",
    "sfax",
    "sousse",
    "gabes",
    "bizerte",
    "kairouan",
    "gafsa",  # Tunisia cities and regions
    "sudan",
    "khartoum",
    "omdurman",
    "port sudan",
    "nyala",
    "kassala",
    "el obeid",
    "al-fashir",
    "dongola",  # Sudan cities and regions
    "western sahara",
    "el aaiun",
    "dakhla",
    "smara",
    "boujdour",  # Western Sahara cities and regions
    # West Africa
    "nigeria",
    "abuja",
    "lagos",
    "kano",
    "ibadan",
    "benin city",
    "port harcourt",
    "kaduna",
    "jos",
    "maiduguri",
    "enugu",
    "onitsha",
    "zaria",  # Nigeria cities and regions
    "ghana",
    "accra",
    "kumasi",
    "tamale",
    "takoradi",
    "tema",
    "cape coast",
    "sunyani",
    "ho",  # Ghana cities and regions
    "senegal",
    "dakar",
    "thies",
    "touba",
    "saint-louis",
    "kaolack",
    "ziguinchor",  # Senegal cities and regions
    "ivory coast",
    "abidjan",
    "yamoussoukro",
    "bouake",
    "daloa",
    "san pedro",
    "korhogo",  # Ivory Coast cities and regions
    "mali",
    "bamako",
    "segou",
    "mopti",
    "koutiala",
    "timbuktu",
    "kidal",
    "gao",  # Mali cities and regions
    "niger",
    "niamey",
    "zinder",
    "maradi",
    "agadez",
    "tahoua",
    "dosso",  # Niger cities and regions
    "burkina faso",
    "ouagadougou",
    "bobo-dioulasso",
    "koudougou",
    "banfora",
    "ouahigouya",
    "dori",  # Burkina Faso cities and regions
    "guinea",
    "conakry",
    "kankan",
    "labé",
    "nzérékoré",
    "kindia",
    "boke",  # Guinea cities and regions
    "sierra leone",
    "freetown",
    "bo",
    "kenema",
    "makeni",
    "kailahun",  # Sierra Leone cities and regions
    "liberia",
    "monrovia",
    "gbarnga",
    "buchanan",
    "ganta",
    "harper",  # Liberia cities and regions
    "benin",
    "porto-novo",
    "cotonou",
    "parakou",
    "abomey",
    "natitingou",
    "ouidah",  # Benin cities and regions
    "togo",
    "lome",
    "sokode",
    "kara",
    "kpalime",
    "atakpame",  # Togo cities and regions
    "gambia",
    "banjul",
    "serrekunda",
    "farafenni",
    "basse santa su",  # Gambia cities and regions
    "mauritania",
    "nouakchott",
    "nouadhibou",
    "zouerate",
    "atar",
    "rosso",  # Mauritania cities and regions
    "cape verde",
    "praia",
    "mindelo",
    "sal",
    "santa maria",  # Cape Verde cities and regions
    "guinea-bissau",
    "bissau",
    "bafata",
    "gabu",
    "cacheu",  # Guinea-Bissau cities and regions
    # Central Africa
    "democratic republic of the congo",
    "kinshasa",
    "lubumbashi",
    "goma",
    "bukavu",
    "kisangani",
    "mbuji-mayi",
    "kananga",
    "kolwezi",  # DRC cities and regions
    "congo",
    "brazzaville",
    "pointe-noire",
    "dolisie",
    "nkayi",
    "ouesso",  # Republic of the Congo cities and regions
    "cameroon",
    "yaounde",
    "douala",
    "garoua",
    "bamenda",
    "maroua",
    "bafoussam",
    "kribi",  # Cameroon cities and regions
    "chad",
    "n'djamena",
    "moundou",
    "sarh",
    "abeche",
    "koumra",
    "faya-largeau",  # Chad cities and regions
    "central african republic",
    "bangui",
    "bimbo",
    "berberati",
    "bambari",
    "bria",
    "bouar",  # CAR cities and regions
    "gabon",
    "libreville",
    "port-gentil",
    "franceville",
    "oyem",
    "moanda",  # Gabon cities and regions
    "equatorial guinea",
    "malabo",
    "bata",
    "ebebiyin",
    "mongomo",  # Equatorial Guinea cities and regions
    "sao tome and principe",
    "sao tome",
    "santo antonio",  # Sao Tome and Principe cities and regions
    "angola",
    "luanda",
    "huambo",
    "lobito",
    "benguela",
    "lubango",
    "malanje",
    "namibe",  # Angola cities and regions
    # East Africa
    "kenya",
    "nairobi",
    "mombasa",
    "kisumu",
    "nakuru",
    "eldoret",
    "nyeri",
    "malindi",  # Kenya cities and regions
    "ethiopia",
    "addis ababa",
    "dire dawa",
    "mekelle",
    "gondar",
    "bahir dar",
    "jimma",
    "awasa",  # Ethiopia cities and regions
    "uganda",
    "kampala",
    "gulu",
    "mbarara",
    "jinja",
    "mbale",
    "arua",  # Uganda cities and regions
    "tanzania",
    "dodoma",
    "dar es salaam",
    "arusha",
    "mbeya",
    "mwanza",
    "zanzibar",
    "tanga",  # Tanzania cities and regions
    "rwanda",
    "kigali",
    "butare",
    "gisenyi",
    "ruhango",
    "nyanza",  # Rwanda cities and regions
    "burundi",
    "bujumbura",
    "gitega",
    "ngozi",
    "rumonge",
    "muyinga",  # Burundi cities and regions
    "somalia",
    "mogadishu",
    "hargeisa",
    "bosaso",
    "kismayo",
    "berbera",  # Somalia cities and regions
    "djibouti",
    "djibouti city",
    "ali sabieh",
    "tadjoura",
    "obock",  # Djibouti cities and regions
    "eritrea",
    "asmara",
    "massawa",
    "keren",
    "assab",
    "mendefera",  # Eritrea cities and regions
    "seychelles",
    "victoria",
    "anse royale",
    "baie lazare",  # Seychelles cities and regions
    "comoros",
    "moroni",
    "mitsamiouli",
    "fomboni",
    "domoni",  # Comoros cities and regions
    "madagascar",
    "antananarivo",
    "toamasina",
    "antsirabe",
    "mahajanga",
    "toliara",  # Madagascar cities and regions
    "mauritius",
    "port louis",
    "curepipe",
    "vacoas-phoenix",
    "beau bassin",  # Mauritius cities and regions
    # Southern Africa
    "south africa",
    "pretoria",
    "cape town",
    "johannesburg",
    "durban",
    "port elizabeth",
    "bloemfontein",
    "polokwane",  # South Africa cities and regions
    "zimbabwe",
    "harare",
    "bulawayo",
    "mutare",
    "gweru",
    "masvingo",
    "kwekwe",
    "victoria falls",  # Zimbabwe cities and regions
    "zambia",
    "lusaka",
    "ndola",
    "kitwe",
    "livingstone",
    "chipata",
    "kabwe",  # Zambia cities and regions
    "namibia",
    "windhoek",
    "swakopmund",
    "walvis bay",
    "oshakati",
    "rundu",
    "keetmanshoop",  # Namibia cities and regions
    "botswana",
    "gaborone",
    "francistown",
    "lobatse",
    "maun",
    "selibe-phikwe",
    "kanye",  # Botswana cities and regions
    "mozambique",
    "maputo",
    "beira",
    "nampula",
    "quelimane",
    "tete",
    "pemba",  # Mozambique cities and regions
    "malawi",
    "lilongwe",
    "blantyre",
    "mzuzu",
    "zomba",  # Malawi cities and regions
    "lesotho",
    "maseru",
    "leribe",
    "mafeteng",
    "mohale's hoek",  # Lesotho cities and regions
    "eswatini",
    "mbabane",
    "manzini",
    "lobamba",
    "piggs peak",  # Eswatini (Swaziland) cities and regions
]

NORTH_AMERICA_REGIONS = [
    # United States
    "united states",
    "washington, d.c.",
    "new york city",
    "los angeles",
    "chicago",
    "houston",
    "phoenix",
    "philadelphia",
    "san antonio",
    "san diego",
    "dallas",
    "san jose",
    "austin",
    "jacksonville",
    "fort worth",
    "columbus",
    "charlotte",
    "san francisco",
    "indianapolis",
    "seattle",
    "denver",
    "boston",
    "el paso",
    "detroit",
    "nashville",
    "memphis",
    "portland",
    "oklahoma city",
    "las vegas",
    "louisville",
    "baltimore",
    "milwaukee",
    "albuquerque",
    "tucson",
    "fresno",
    "sacramento",
    "kansas city",
    "mesa",
    "atlanta",
    "miami",
    "orlando",
    "tampa",
    "st. louis",  # Major US cities
    "california",
    "texas",
    "florida",
    "new york",
    "pennsylvania",
    "ohio",
    "illinois",
    "georgia",
    "north carolina",
    "michigan",
    "arizona",
    "new jersey",
    "virginia",
    "massachusetts",
    "washington",
    "indiana",
    "tennessee",
    "missouri",
    "maryland",
    "wisconsin",
    "colorado",
    "minnesota",
    "south carolina",
    "alabama",
    "louisiana",
    "kentucky",
    "oregon",
    "oklahoma",
    "connecticut",
    "iowa",
    "mississippi",
    "arkansas",
    "utah",
    "nevada",
    "new mexico",
    "west virginia",
    "nebraska",
    "idaho",
    "hawaii",
    "maine",
    "new hampshire",
    "rhode island",
    "montana",
    "delaware",
    "south dakota",
    "north dakota",
    "alaska",
    "wyoming",
    "vermont",  # US states
    # Canada
    "canada",
    "ottawa",
    "toronto",
    "vancouver",
    "montreal",
    "calgary",
    "edmonton",
    "winnipeg",
    "quebec city",
    "hamilton",
    "kitchener",
    "london",
    "victoria",
    "halifax",
    "windsor",
    "saskatoon",
    "regina",
    "st. john's",
    "fredericton",
    "charlottetown",
    "yellowknife",  # Major Canadian cities
    "ontario",
    "quebec",
    "british columbia",
    "alberta",
    "manitoba",
    "saskatchewan",
    "nova scotia",
    "new brunswick",
    "newfoundland and labrador",
    "prince edward island",
    "northwest territories",
    "yukon",
    "nunavut",  # Canadian provinces and territories
    # Greenland
    "greenland",
    "nuuk",
    "sisimiut",
    "ilulissat",
    "qaqortoq",  # Greenland cities and regions
]

LATIN_AMERICA_AND_CARIBEAN_REGIONS =[
    # Mexico
    "mexico",
    "mexico city",
    "guadalajara",
    "monterrey",
    "puebla",
    "tijuana",
    "leon",
    "merida",
    "ciudad juarez",
    "zapopan",
    "acapulco",
    "cancun",
    "toluca",
    "queretaro",
    "saltillo",
    "veracruz",
    "culiacan",
    "chihuahua",
    "hermosillo",
    "aguascalientes",  # Major Mexican cities
    "jalisco",
    "nuevo leon",
    "mexico state",
    "yucatan",
    "quintana roo",
    "veracruz",
    "puebla",
    "guanajuato",
    "chihuahua",
    "sonora",
    "baja california",
    "coahuila",
    "zacatecas",
    "tamaulipas",
    "oaxaca",
    "chiapas",
    "sinaloa",
    "tabasco",
    "san luis potosi",
    "durango",
    "hidalgo",
    "michoacan",
    "morelos",
    "tlaxcala",
    "colima",
    "campeche",
    "aguascalientes",
    "queretaro",
    "baja california sur",  # Mexican states
    # Central America
    "guatemala",
    "guatemala city",
    "mixco",
    "villa nueva",
    "quetzaltenango",
    "escuintla",  # Guatemala cities and regions
    "belize",
    "belize city",
    "belmopan",
    "san ignacio",
    "orange walk",  # Belize cities and regions
    "honduras",
    "tegucigalpa",
    "san pedro sula",
    "la ceiba",
    "choloma",
    "el progreso",  # Honduras cities and regions
    "el salvador",
    "san salvador",
    "santa ana",
    "soyapango",
    "san miguel",  # El Salvador cities and regions
    "nicaragua",
    "managua",
    "leon",
    "granada",
    "matagalpa",
    "masaya",  # Nicaragua cities and regions
    "costa rica",
    "san jose",
    "limon",
    "alajuela",
    "heredia",
    "puntarenas",  # Costa Rica cities and regions
    "panama",
    "panama city",
    "colón",
    "david",
    "santiago",
    "la chorrera",  # Panama cities and regions
    # South America
    "argentina",
    "buenos aires",
    "cordoba",
    "rosario",
    "mendoza",
    "la plata",
    "tucuman",
    "salta",
    "santa fe",  # Argentina cities and regions
    "brazil",
    "brasília",
    "rio de janeiro",
    "sao paulo",
    "salvador",
    "fortaleza",
    "belo horizonte",
    "manaus",
    "recife",
    "curitiba",
    "porto alegre",
    "goiania",
    "belem",
    "campinas",  # Brazil cities and regions
    "chile",
    "santiago",
    "valparaiso",
    "concepcion",
    "la serena",
    "antofagasta",
    "temuco",
    "iquique",  # Chile cities and regions
    "colombia",
    "bogota",
    "medellin",
    "cali",
    "barranquilla",
    "cartagena",
    "bucaramanga",
    "pereira",
    "cucuta",  # Colombia cities and regions
    "venezuela",
    "caracas",
    "maracaibo",
    "valencia",
    "barquisimeto",
    "ciudad guayana",
    "maturin",
    "merida",  # Venezuela cities and regions
    "peru",
    "lima",
    "arequipa",
    "trujillo",
    "chiclayo",
    "piura",
    "cusco",
    "ica",  # Peru cities and regions
    "ecuador",
    "quito",
    "guayaquil",
    "cuenca",
    "machala",
    "manta",  # Ecuador cities and regions
    "bolivia",
    "la paz",
    "santa cruz",
    "cochabamba",
    "sucre",
    "oruro",
    "potosi",  # Bolivia cities and regions
    "paraguay",
    "asuncion",
    "ciudad del este",
    "luque",
    "san lorenzo",
    "lambare",  # Paraguay cities and regions
    "uruguay",
    "montevideo",
    "salto",
    "paysandu",
    "las piedras",
    "rivera",  # Uruguay cities and regions
    "guyana",
    "georgetown",
    "linden",
    "new amsterdam",  # Guyana cities and regions
    "suriname",
    "paramaribo",
    "lelydorp",
    "nieuw nickerie",  # Suriname cities and regions
    "french guiana",
    "cayenne",
    "kourou",
    "saint-laurent-du-maroni",  # French Guiana cities and regions
    # The Caribbean
    "bahamas",
    "nassau",
    "freeport",
    "lucaya",  # Bahamas cities and regions
    "cuba",
    "havana",
    "santiago de cuba",
    "camaguey",
    "holguin",
    "guantanamo",  # Cuba cities and regions
    "jamaica",
    "kingston",
    "montego bay",
    "spanish town",
    "portmore",
    "mandeville",  # Jamaica cities and regions
    "haiti",
    "port-au-prince",
    "cap-haitien",
    "les cayes",
    "gonayiv",  # Haiti cities and regions
    "dominican republic",
    "santo domingo",
    "santiago",
    "la romana",
    "puerto plata",
    "san pedro de macorís",  # Dominican Republic cities and regions
    "puerto rico",
    "san juan",
    "ponce",
    "mayaguez",
    "bayamon",
    "caguas",  # Puerto Rico cities and regions
    "trinidad and tobago",
    "port of spain",
    "san fernando",
    "chaguanas",  # Trinidad and Tobago cities and regions
    "barbados",
    "bridgetown",
    "speightstown",
    "holetown",
    "oistins",  # Barbados cities and regions
    "dominica",
    "roseau",
    "portsmouth",  # Dominica cities and regions
    "saint lucia",
    "castries",
    "soufriere",  # Saint Lucia cities and regions
    "saint vincent and the grenadines",
    "kingstown",
    "georgetown",  # Saint Vincent and the Grenadines cities and regions
    "grenada",
    "saint george's",
    "gouyave",  # Grenada cities and regions
    "antigua and barbuda",
    "saint john's",
    "codrington",  # Antigua and Barbuda cities and regions
    "saint kitts and nevis",
    "basseterre",
    "charlestown",  # Saint Kitts and Nevis cities and regions
    # Other Caribbean Territories
    "anguilla",
    "the valley",  # Anguilla
    "aruba",
    "oranjestad",  # Aruba
    "bermuda",
    "hamilton",
    "st. george's",  # Bermuda
    "british virgin islands",
    "road town",  # British Virgin Islands
    "cayman islands",
    "george town",  # Cayman Islands
    "curacao",
    "willemstad",  # Curacao
    "guadeloupe",
    "basse-terre",
    "pointe-à-pitre",  # Guadeloupe
    "martinique",
    "fort-de-france",
    "le lamentin",  # Martinique
    "saint barthelemy",
    "gustavia",  # Saint Barthelemy
    "saint martin",
    "marigot",  # Saint Martin (French)
    "saint maarten",
    "philipsburg",  # Sint Maarten (Dutch)
    "turks and caicos islands",
    "cockburn town",  # Turks and Caicos Islands
    "u.s. virgin islands",
    "charlotte amalie",  # U.S. Virgin Islands
]

OCEANIA_REGIONS = [
    # Australia
    "australia",
    "canberra",
    "sydney",
    "melbourne",
    "brisbane",
    "perth",
    "adelaide",
    "gold coast",
    "newcastle",
    "canberra",
    "hobart",
    "darwin",  # Australian cities
    "new south wales",
    "victoria",
    "queensland",
    "western australia",
    "south australia",
    "tasmania",
    "northern territory",
    "australian capital territory",  # Australian states and territories
    # New Zealand
    "new zealand",
    "wellington",
    "auckland",
    "christchurch",
    "hamilton",
    "dunedin",
    "tauranga",
    "palmerston north",
    "napier-hastings",  # New Zealand cities
    "north island",
    "south island",  # New Zealand regions
    # Papua New Guinea
    "papua new guinea",
    "port moresby",
    "lae",
    "mount hagen",
    "madang",
    "kokopo",
    "goroka",
    "popondetta",  # Papua New Guinea cities and regions
    "eastern highlands",
    "morobe",
    "east new britain",
    "western province",
    "southern highlands",
    "madang province",  # Papua New Guinea provinces
    # Fiji
    "fiji",
    "suva",
    "lautoka",
    "nadi",
    "labasa",
    "sigatoka",  # Fiji cities
    "viti levu",
    "vanua levu",  # Major islands of Fiji
    # Solomon Islands
    "solomon islands",
    "honiara",
    "gizo",
    "auki",
    "kirakira",  # Solomon Islands cities and regions
    "guadalcanal",
    "malaita",
    "western province",  # Solomon Islands provinces
    # Vanuatu
    "vanuatu",
    "port vila",
    "luganville",
    "lenakel",  # Vanuatu cities and regions
    "efate",
    "espiritu santo",
    "tanna",  # Major islands of Vanuatu
    # Samoa
    "samoa",
    "apia",
    "salelologa",  # Samoa cities and regions
    "upolu",
    "savai'i",  # Samoa islands
    # Tonga
    "tonga",
    "nuku'alofa",
    "neiafu",
    "pangai",  # Tonga cities and regions
    "tongatapu",
    "vava'u",
    "ha'apai",  # Tonga islands and island groups
    # Palau
    "palau",
    "ngerulmud",
    "koror",
    "melekeok",  # Palau cities and regions
    "babeldaob",
    "koror island",
    "peleliu",  # Major islands of Palau
    # Micronesia (Federated States of Micronesia)
    "micronesia",
    "palikir",
    "kolonia",
    "weno",
    "tofol",  # Micronesia cities and regions
    "pohnpei",
    "chuuk",
    "yap",
    "kosrae",  # Micronesia states
    # Kiribati
    "kiribati",
    "tarawa",
    "betio",
    "bikenibeu",  # Kiribati cities and regions
    "gilbert islands",
    "phoenix islands",
    "line islands",  # Kiribati island groups
    # Marshall Islands
    "marshall islands",
    "majuro",
    "ebeye",
    "jaluit",  # Marshall Islands cities and regions
    "ratak chain",
    "ralik chain",  # Marshall Islands island groups
    # Nauru
    "nauru",
    "yaren",
    "aiwo",
    "buada",  # Nauru cities and regions
    # Tuvalu
    "tuvalu",
    "funafuti",
    "vaiaku",
    "nanumea",  # Tuvalu cities and regions
    "funafuti atoll",
    "nanumea atoll",
    "nukufetau atoll",  # Tuvalu atolls
    # New Caledonia (French Territory)
    "new caledonia",
    "noumea",
    "mont-dore",
    "dumbea",
    "paita",  # New Caledonia cities
    "grande terre",
    "loyalty islands",
    "iles des pines",  # New Caledonia islands and regions
    # French Polynesia (French Territory)
    "french polynesia",
    "papeete",
    "faaa",
    "mahina",
    "punaauia",  # French Polynesia cities
    "tahiti",
    "moorea",
    "bora bora",
    "marquesas islands",
    "tuamotu archipelago",
    "austral islands",
    "gambier islands",  # French Polynesia islands and archipelagos
    # Guam (US Territory)
    "guam",
    "hagatna",
    "dededo",
    "tamuning",
    "yigo",  # Guam cities and regions
    # Northern Mariana Islands (US Territory)
    "northern mariana islands",
    "saipan",
    "tinian",
    "rota",  # Northern Mariana Islands cities and regions
    # American Samoa (US Territory)
    "american samoa",
    "pago pago",
    "tutuila",
    "ta'u",
    "ofu",  # American Samoa cities and regions
    # Other Pacific Islands
    "pitcairn islands",
    "adamstown",  # Pitcairn Islands (UK Territory)
    "tokelau",
    "atafu",
    "nukunonu",
    "fakaofo",  # Tokelau (NZ Territory)
    # Other External Territories of Oceania
    "cook islands",
    "rarotonga",
    "avarua",  # Cook Islands (self-governing in free association with New Zealand)
    "niue",
    "alofi",  # Niue (self-governing in free association with New Zealand)
    "wallis and futuna",
    "mata-utu",  # Wallis and Futuna (French Territory)
]
